# Data Configuration
data:
  raw_data_path: "data/raw_data"  # Path where raw audio files are stored
  processed_data_path: "data/processed_data"  # Path to store preprocessed data (e.g., MFCCs)
  audio_file_extension: ".wav"  # Expected audio file format

# Model Configuration
model:
  input_shape: [128, 128, 3]  # Example: shape of spectrogram input (height, width, channels)
  num_classes: 10  # Number of genres
  batch_size: 32  # Batch size for training
  epochs: 50  # Number of epochs to train
  learning_rate: 0.0001  # Learning rate for optimizer
  optimizer: "adam"  # Optimizer type
  model_save_path: "models/music_genre_model.h5"  # Path to save trained model

# Training Configuration
training:
  validation_split: 0.2  # Fraction of data to use for validation
  random_seed: 42  # Random seed for reproducibility

# Logging Configuration
logging:
  log_dir: "logs"  # Directory to save training logs (e.g., TensorBoard logs)
  log_frequency: 10  # How often to log (e.g., every 10 steps)
  
# Flask API Configuration
flask:
  host: "0.0.0.0"  # Host for Flask app
  port: 5000  # Port for Flask app

# DVC Configuration (if using DVC for data versioning)
dvc:
  data_version: "v1"  # Data version for DVC tracking
